disabled = false
languageCode = "zh-tw"
languageName = "繁體中文"
weight = 1
title = "KAI WIKI"

[params]
  showLanguageSelector = true
  displayName = "ZH"
  isoCode = "zh"
  dateFormat = "2006/01/02"
  # logo = "/kaistudio.jpg"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"


[params.author]
  name = "KAI"
  email = "kai10050621@gmail.com"
  #headline = ""
  #bio = ""
   links = [
      { discord = "https://discord.gg/BA6sG4fZxA" },
      { github = "https://github.com/Kaihchs118" },
      { instagram = "https://www.instagram.com/kkai_0621/" },
      { youtube = "https://www.youtube.com/@kaistudio-621" },
      # { email = "kai10050621@gmail.com" },
      # { link = "https://link-to-some-website.com/" },
      # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
      # { apple = "https://www.apple.com" },
      # { blogger = "https://username.blogspot.com/" },
      # { bluesky = "https://bsky.app/profile/username" },
      # { codepen = "https://codepen.io/username" },
      # { dev = "https://dev.to/username" },
      # { dribbble = "https://dribbble.com/username" },
      # { facebook = "https://facebook.com/username" },
      # { flickr = "https://www.flickr.com/photos/username/" },
      # { foursquare = "https://foursquare.com/username" },
      # { gitlab = "https://gitlab.com/username" },
      # { Google = "https://www.google.com/" },
      # { hashnode = "https://username.hashnode.dev" },
      # { itch-io = "https://username.itch.io" },
      # { keybase = "https://keybase.io/username" },
      # { keyoxide = "https://keyoxide.org/URI" },
      # { kickstarter = "https://www.kickstarter.com/profile/username" },
      # { lastfm = "https://lastfm.com/user/username" },
      # { linkedin = "https://linkedin.com/in/username" },
      # { mastodon = "https://mastodon.instance/@username" },
      # { matrix = "https://matrix.to/ /URI" },
      # { medium = "https://medium.com/username" },
      # { microsoft = "https://www.microsoft.com/" },
      # { orcid = "https://orcid.org/userid" },
      # { patreon = "https://www.patreon.com/username" },
      # { pinterest = "https://pinterest.com/username" },
      # { reddit = "https://reddit.com/user/username" },
      # { researchgate = "https://www.researchgate.net/profile/username" },
      # { signal = "https://signal.me/ eu/userid" },
      # { slack = "https://workspace.url/team/userid" },
      # { snapchat = "https://snapchat.com/add/username" },
      # { soundcloud = "https://soundcloud.com/username" },
      # { spotify = "https://open.spotify.com/user/userid" },
      # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
      # { steam = "https://steamcommunity.com/profiles/userid" },
      # { telegram = "https://t.me/username" },
      # { threads = "https://www.threads.net/@username" },
      # { tiktok = "https://tiktok.com/@username" },
      # { tumblr = "https://username.tumblr.com" },
      # { twitch = "https://twitch.tv/username" },
      # { twitter = "https://twitter.com/username" },
      # { x-twitter = "https://twitter.com/username" },
      # { whatsapp = "https://wa.me/phone-number" },
      # { ko-fi = "https://ko-fi.com/username" },
      # { codeberg = "https://codeberg.org/username"},
    ]
